#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "rspamd"
name = "Rspamd"

description.en = "Spam filtering system"
description.fr = "Système pour filtrer les spams"

version = "4.0.1~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://rspamd.com/"
admindoc = "https://rspamd.com/doc"
code = "https://github.com/rspamd/rspamd"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources.trixie]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.1-1~8700333~trixie_amd64.deb"
    amd64.sha256 = "2ff94a79377f4fa2161e053375babad74a2bf9e67bd879c178c28bce1fec2b07"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.1-1~8700333~trixie_arm64.deb"
    arm64.sha256 = "4e31f3bda328fe08805f4b378d1c7fc8a79f2af4b7121ac2637e9a8ec02620f9"
    extract = false
    rename = "rspamd.deb"

    [resources.sources.bookworm]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.1-1~8700333~bookworm_amd64.deb"
    amd64.sha256 = "5a560ed54d8202fa3cdf6f24cc5bebe07d93bf49d063d74bf6525cc71f7c446f"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.1-1~8700333~bookworm_arm64.deb"
    arm64.sha256 = "771231481c9b57a84750bed3cd2df46f54cd48eb30cb6c2676d73bd33419f22b"
    extract = false
    rename = "rspamd.deb"
    
    [resources.permissions]

    [resources.apt]
    packages = "redis-server, libhyperscan5, postfix, libsodium23, libsqlite3-0, libssl3, libarchive13, libbinutils"
