#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "rspamd"
name = "Rspamd"

description.en = "Spam filtering system"
description.fr = "Système pour filtrer les spams"

version = "4.0.0~ynh1"

maintainers = []

[upstream]
license = "Apache-2.0"
website = "https://rspamd.com/"
admindoc = "https://rspamd.com/doc"
code = "https://github.com/rspamd/rspamd"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources.trixie]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.0-1~4a2ab73~trixie_amd64.deb"
    amd64.sha256 = "4e4741bd33096a86ef564f27388dab03f53330f50936edc7958e18bb185e8923"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.0-1~4a2ab73~trixie_arm64.deb"
    arm64.sha256 = "cd3bc534a07b18ce3249f211befbb9e28e23a22df29fd283d709329194357ea8"
    extract = false
    rename = "rspamd.deb"

    [resources.sources.bookworm]
    amd64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.0-1~4a2ab73~bookworm_amd64.deb"
    amd64.sha256 = "41df8e392c795635b2e0a219f434a04b69853ddd7d56d8933c90839c54c6355f"
    arm64.url = "https://rspamd.com/apt-stable/pool/main/r/rspamd/rspamd_4.0.0-1~4a2ab73~bookworm_arm64.deb"
    arm64.sha256 = "4a1eb8c0c3aa263f315cc6666a56dc72b3aff337eead27c54b98781db9fb3248"
    extract = false
    rename = "rspamd.deb"
    
    [resources.permissions]

    [resources.apt]
    packages = "redis-server, libhyperscan5, postfix, libsodium23, libsqlite3-0"
    packages_from_raw_bash = """
        if [[ "$(lsb_release -sc)" == "trixie" ]]; then
            echo "libssl3t64, libarchive13t64, libicu76, libbinutils"
        else
            echo "libssl3, libarchive13, libicu72, libbinutils"
        fi
    """
