# Jochen added on 21.4.2026 more aggressive SPAM filter
reject = 12;           # default 15 — outright reject
add_header = 4;        # default 6  — mark as spam, delivered to Junk
greylist = 2;          # default 4  — delay suspicious mail
