## /etc/rspamd/local.d/rbl.conf
## Enable additional RBL providers. Names must match block names in modules.d/rbl.conf.
## DBL is enabled by default already; we explicitly enable spamhaus zen here.

rbls {
    spamhaus {
        enabled = true;
    }
    SPAMHAUS_ZEN_URIBL {
        enabled = true;
    }
    mailspike {
        enabled = true;
    }
    blocklistde {
        enabled = true;
    }
    virusfree {
        enabled = true;
    }
}
