#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
    yunohost service remove $app
fi

# Remove postfix conf tweak
ynh_safe_rm "/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix

# Remove rspamd conf
ynh_safe_rm "/etc/rspamd/local.d/redis.conf"
ynh_safe_rm "/etc/rspamd/local.d/classifier-bayes.conf"
ynh_safe_rm "/etc/rspamd/local.d/dkim_signing.conf"

# Remove custom rspamd configuration (aggressive spam filtering, blocklists, custom Lua rules)
ynh_safe_rm "/etc/rspamd/local.d/actions.conf"
ynh_safe_rm "/etc/rspamd/local.d/dmarc.conf"
ynh_safe_rm "/etc/rspamd/local.d/groups.conf"
ynh_safe_rm "/etc/rspamd/local.d/multimap.conf"
ynh_safe_rm "/etc/rspamd/local.d/rbl.conf"
ynh_safe_rm "/etc/rspamd/local.d/maps.d"
ynh_safe_rm "/etc/rspamd/lua.local.d/custom_spam_rules.lua"

# Remove dovecot conf
ynh_safe_rm /etc/dovecot/yunohost.d/post-ext.d/antispam.conf
ynh_safe_rm /usr/lib/dovecot/sieve/report-spam.sieve
ynh_safe_rm /usr/lib/dovecot/sieve/report-spam.svbin
ynh_safe_rm /usr/lib/dovecot/sieve/report-ham.sieve
ynh_safe_rm /usr/lib/dovecot/sieve/report-ham.svbin
ynh_safe_rm /usr/lib/dovecot/sieve/rspamd-learn-spam.sh
ynh_safe_rm /usr/lib/dovecot/sieve/rspamd-learn-ham.sh

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_systemctl --service=postfix --action=restart

ynh_systemctl --service=dovecot --action=restart

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
